name: PHPStan

on: [push]

jobs:
    phpstan:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.4

            - name: Install dependencies
              run: composer install --no-interaction --no-progress

            - name: Run PHPStan
              run: vendor/bin/phpstan analyse
